[build]
command = "npm install && npm run generate-index && npm run generate-agenda && node generate-albums-index.js && npm run generate-affiches && npm run generate-agenda-mfp && npm run generate-temoignages-mfp && npm run build"
publish = "."

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

