[build]
  publish = "."
  command = "npm install && npm run generate-index && npm run generate-agenda && npm run generate-agenda-mfp && node generate-albums-index.js && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200