[build]
  command = "npm install && npm run generate-index && npm run generate-agenda && node generate-albums-index.js && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
